# Generated by Django 4.0.5 on 2022-06-15 13:16

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_item_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(default=api.models.generate_unique_code, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='writer',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
