# Generated by Django 4.0.5 on 2022-06-20 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_item_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_song',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
