# Generated by Django 4.0.5 on 2022-06-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_item_current_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='current_song',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
