# Generated by Django 4.0.5 on 2022-06-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_item_current_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='image'),
        ),
    ]
