# Generated by Django 4.0.5 on 2022-06-22 11:33

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to, verbose_name='image'),
        ),
    ]
