# Generated by Django 4.0.5 on 2022-06-30 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='writer',
        ),
    ]
