# Generated by Django 4.0.5 on 2022-07-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_user_cart_writer'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('writer', 'item'), name='user-polled'),
        ),
    ]
